#!/bin/bash

playing=$(xdotool search --class "spotify" | tail -1)

name=$(xdotool getwindowname $playing | sed 's/ Premium//' )

if [[ $name = "Spotify" ]]; then

    print=" Paused ⏸"
elif [[ $name = "" ]]; then

    print=" Not Playing ■"
else

    print=" ▶ $name "
fi

echo $print # full text
echo $print # short text

# color
if [ "$print" = " Not Playing ■" ]; then
    echo "#E06B74"
elif [ "$print" = " Paused ⏸" ]; then
    echo "#C678DD"
else
    echo "#56B6C2"
fi
    
