#!/bin/bash

echo "Starting pdfsort ... "

echo "Check for previous instances and killing them ..."

PIDS=`ps cax | grep inotifywait | grep -o '^[ ]*[0-9]*'` 

if [ ! -z "$PIDS" ]; then
    for PID in $PIDS; do
        kill $PID
    done
fi

# Set some path variables
path=$HOME/Downloads
tmp=/tmp/pdfDirectory

inotifywait -m --format "%f" -e moved_to "$path" | while read file;do

    if [[ $file == *.pdf ]];then
        
        if [[ ! -d "$tmp" ]];then mkdir "$tmp";fi

        mv "$path/$file" "$tmp/$file"
        nohup xdg-open "$tmp/$file" &> /dev/null &
        notify-send -t 5000 "$file opened in Zathura"

    fi
done
