#!/bin/bash

# Bash Script Wrapper for PDF-Grep

# Request Directory
directory(){

    while :;do
    # Option Selecions
        case $select in

        "-d") echo -n "Input Directory : "
            read "directory"

            if [ -d "$directory" ]; then

                echo "Found $directory."
                file=$directory
                break
            else

                echo "Directory not found."
            fi
            ;;
        "-f") echo -n "Input File : "
            read "file"
            if [ -f "$file" ]; then

                echo "Found $file."
                option=""
                break
            else

                echo "File not found."
            fi
            ;;
        "-h") echo "--------------------- Help --------------------"
            echo "searchpdf [option]\n"
            echo -e "Options :\n\n\t -f Search file\n\t -d Search directory"
            exit
            ;;
        *) echo "Option not found."
            ;;
        esac
    done
}

# Search Function
search(){

    echo -n "Search term : "
    read searchTerm
    
    # Uses pdfgrep to search defined location
    if [ "$select" = "-d" ]; then

        pdfgrep --cache -i -n -r "$searchTerm" "$file"
    elif [ "$select" = "-f" ]; then

        pdfgrep --cache -i -n "$searchTerm" "$file"
    fi
}

# Main Function
main(){
	
    echo "------------------ search-pdf -----------------"
    
    search

    echo "--------------------- Done --------------------"
}

# Actual Execution
select=$1
directory

while :;do
    
    main
done
