#!/bin/bash

# Accepts input as Binary(b), Hexadecimal(h) and Decimal(d) and converts to the other two and prints to the command line.

while [ "$1" != "" ];do
    case $1 in
        -b )    DEC=$(echo "obase=10; ibase=2; $2" | bc)
                HEX=$(echo "obase=16; ibase=2; $2" | bc)
                echo -e "     Binary : \t$2 \n    Decimal : \t$DEC \nHexadecimal : \t$HEX"
                break
                ;;
        -d )    BIN=$(echo "obase=2; ibase=10; $2" | bc)
                HEX=$(echo "obase=16; ibase=10; $2" | bc)
                echo -e "     Binary : \t$BIN \n    Decimal : \t$2 \nHexadecimal : \t$HEX"
                break
                ;;
        -h )    DEC=$(echo "obase=10; ibase=16; $2" | bc)
                BIN=$(echo "obase=2; ibase=16; $2" | bc)
                echo -e "     Binary : \t$BIN \n    Decimal : \t$DEC \nHexadecimal : \t$2"
                break
                ;;
        * )     echo -e "# Help\n\t-b\tConvert from binary\n\t-d\tConvert from decimal\n\t-h\tConvert from hexadecimal\n\t*\tPrints this\n"
                exit 1
                ;;
    esac
done


