#!/bin/bash

# Caffine Mode (Don't turn off displays!)

DPMS=$(xset q | grep "DPMS is" | awk '{ print $3 }')

if [[ "$DPMS" == "Enabled" ]];then

    xset s off -dpms
else

    xset s 600 600
    xset dpms 600 600 600
fi
