#!/bin/sh

# Define some colours.
aqua="#8be9fd"
black="#161315"
blue="#6272a4"
green="#50fa7b"
purple="#bd93f9"
red="#ff5555"
white="#f8f8f2"
yellow="#f1fa8c"

lock() {
    i3lock \
    --insidevercolor=$black \
    --ringvercolor=$yellow \
    --insidewrongcolor=$black \
    --ringwrongcolor=$red \
    --insidecolor=$black \
    --ringcolor=$black \
    --linecolor=$black \
    --separatorcolor=$blue \
    --verifcolor=$yellow \
    --wrongcolor=$red \
    --timecolor=$white \
    --datecolor=$white \
    --layoutcolor=$aqua \
    --keyhlcolor=$white \
    --bshlcolor=$white \
    --blur 8 \
    --veriftext="Checking ..." \
    --wrongtext="Wrong." \
    --clock \
    --indicator \
    --timestr="%H:%M:%S" \
    --datestr="%A, %m %Y"
}

lock
